vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.completeopt:remove({ "preview" })
vim.opt.signcolumn = "auto"
vim.opt.termguicolors = true
vim.opt.undofile = true
vim.opt.scrolloff = 5
vim.opt.cmdheight = 1
vim.opt.updatetime = 100
vim.opt.swapfile = false
vim.opt.incsearch = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.mouse = ""
