return {}
-- return {
--   "echasnovski/mini.completion",
--   event = "InsertEnter",
--   opts = {
--     window = {
--       info = {
--         height = 25,
--         width = 80,
--         border = "single",
--       },
--       signature = {
--         height = 25,
--         width = 80,
--         border = "single",
--       },
--     },
--     lsp_completion = {
--       source_func = "omnifunc",
--       auto_setup = false,
--     },
--   },
-- }
