vim.keymap.set("n", "<C-c>", function()
  local marked_files = vim.fn["netrw#Expose"]("netrwmarkfilelist")
  io.popen("xclip-copyfile " .. table.concat(marked_files, " "))
  print("Copied files to system clipboard")
end, { buffer = true })

vim.keymap.set("n", "<C-v>", function()
  local current_netrw_buffer = vim.fn.expand("%")
  vim.cmd.cd(current_netrw_buffer)
  io.popen("xclip-pastefile")
  vim.cmd["cd!"]("-")
end, { buffer = true })
